### ISSUE TITLE
can reproduce a bug in ctrl-z

### ISSUE THREAD

**Issue by klesun** [klesun/shmidusic#131]
type some note from synth or keyboard
go to a random place and delete several chords with menu
go some steps back and remove a chard again
do ctrl-z two (maybe more) times
!!! profit

```
midiana crashed with message [Fatal: final field not present in json! staffList] 
but i successed saving backup of your project into file 
[/home/klesun/mounted_fat/progas/shmidusic/bin/savedJustBeforeFatal/fatal_backup_2016-01-10-22-53-49.bs.json]
stack trace: 

java.lang.Throwable
	at org.shmidusic.stuff.tools.Logger.fatal(Logger.java:26)
	at org.klesun_model.IModel.reconstructFromJson(IModel.java:42)
	at org.shmidusic.sheet_music.SheetMusic.<init>(SheetMusic.java:17)
	at org.klesun_model.Explain.lambda$map$36(Explain.java:81)
	at org.klesun_model.Explain.ifSuccess(Explain.java:65)
	at org.klesun_model.Explain.map(Explain.java:81)
	at org.shmidusic.MainPanel.undo(MainPanel.java:100)
	at org.shmidusic.sheet_music.SheetMusicComponent$1.lambda$getMyClassActionMap$20(SheetMusicComponent.java:63)
	at org.klesun_model.ContextAction.redo(ContextAction.java:64)
	at org.klesun_model.IKeyHandler.handleKey(IKeyHandler.java:33)
	at org.shmidusic.sheet_music.SheetMusicComponent.lambda$new$22(SheetMusicComponent.java:74)
	at org.shmidusic.stuff.tools.Fp$1.keyPressed(Fp.java:24)

**Comment by klesun** [comment]
likely fixed in ab500e571f67ee32996ecf43ed3ca20d4ae1cb7b
